### ISSUE TITLE
Загрузка изображений через админку выпадает в ошибку

### ISSUE THREAD

**Issue by Suzanskyi** [ivan909020/shop-telegram-bot#4]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Jun 13 12:55:52 EEST 2020
There was an unexpected error (type=Internal Server Error, status=500).
Failed save photo
ua.ivan909020.admin.exceptions.FailedSaveFileException: Failed save photo
	at ua.ivan909020.admin.services.impl.PhotoStorageServiceDefault.store(PhotoStorageServiceDefault.java:32)
	at ua.ivan909020.admin.controllers.ProductController.updateProduct(ProductController.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)

**Comment by ivan-zaitsev** [comment]
В конфиге нужно указать путь к папке в которую будут сохраняться изображения. Если папка не создана то будет исключение.

**Comment by Suzanskyi** [comment]
> В конфиге нужно указать путь к папке в которую будут сохраняться изображения. Если папка не создана то будет исключение.

Спасибо, получилось. Но еще одна ошибка в том, что не отображаются фотки, на сервере они загружены. Может права нужны какие то? 
![image](https://user-images.githubusercontent.com/18307543/84567780-91672b00-ad83-11ea-861a-2d17efe26dcd.png)

**Comment by ivan-zaitsev** [comment]
> > В конфиге нужно указать путь к папке в которую будут сохраняться изображения. Если папка не создана то будет исключение.
> 
> Спасибо, получилось. Но еще одна ошибка в том, что не отображаются фотки, на сервере они загружены. Может права нужны какие то?
> ![image](https://user-images.githubusercontent.com/18307543/84567780-91672b00-ad83-11ea-861a-2d17efe26dcd.png)

В конфигурации админ панели нужно изменить ссылку(http://localhost:8080) на ссылку вашего сервера. Параметр admin.server-url
